---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: centos7
    driver:
      box: centos7-mysql

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
